version: '3'
services:

  ##
  ## Nginx entry point
  ##
  nginx:
    restart: always
    image: jwilder/nginx-proxy:alpine
    
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx_dhparam:/etc/nginx/dhparam"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_certs:/etc/nginx/certs"
       
    depends_on:
    - assistant

    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
      - default
  
  ##
  ## Letsencrypt-Companion
  ##
  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx_dhparam:/etc/nginx/dhparam"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_certs:/etc/nginx/certs"

    depends_on:
      - nginx
    
    networks:
      - internal
  
  # The main assistant
  assistant:
    restart: always
    image: kwarc/cla-assistant
    
    depends_on:
      - mongo

    environment:
      - VIRTUAL_HOST=${DOMAINNAME}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=${DOMAINNAME}
      - LETSENCRYPT_EMAIL=${LEEMAIL}
      - PORT=5000
      - PROTOCOL=http
      - HOST=0.0.0.0
      - MONGODB=mongodb://${MONGO_ROOTUSER}:${MONGO_ROOTPASS}@mongo:27017/cla_assistant
      - GITHUB_CLIENT=${GITHUB_CLIENT}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASS=${GITHUB_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_ADMIN_USERS=${GITHUB_ADMIN}
    
    networks:
      - internal
  
  mongo:
    restart: always
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOTUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOTPASS}
      - MONGO_INITDB_DATABASE=cla_assistant
    volumes:
      - mongo:/data/db
    
    networks:
      - internal

volumes:
  mongo:
  nginx_vhost:
  nginx_certs:
  nginx_html:
  nginx_dhparam:


networks:
  internal: